"""new fields in user model

Revision ID: 25897485c3ea
Revises: e39b658e9cfd
Create Date: 2022-07-08 09:21:50.230066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25897485c3ea'
down_revision = 'e39b658e9cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
